export const collegeObjects = [
    { name: "Abhay Phansikar", college: "Chair, IEEE Bombay Section" },
    { name: "Anthony Thomas", college: "CIO, Nissan Motor Corporation, Japan" },
    {
      name: "Arogyaswamy Paulraj",
      college: "Professor (Emeritus), Stanford University, USA",
    },
    { name: "Asheesh K Singh", college: "Chair, IEEE UP Section" },
    { name: "Celia Shahnaz", college: "Professor, BUET, Dhaka, Bangladesh" },
    { name: "Deepak Mathur", college: "IEEE Region 10 Director Elect, India" },
    { name: "Dinanath Kholkar", college: "Chair, IEEE Pune Section" },
    { name: "Fitri Yuli Zulkifli", college: "Chair, IEEE Indonesia Section" },
    { name: "Harish Mysore", college: "Director, GIEEE, Bangalore, India" },
    { name: "HR Mohan", college: "Editor, IEEE India Council Newsletter" },
    { name: "Jim Jefferies", college: "IEEE Past President, USA" },
    { name: "Jose M.F. Moura", college: "IEEE President & CEO, USA" },
    { name: "Karen Bartleson", college: "IEEE Past President, USA" },
    { name: "Keshav Bapat", college: "Chair, IEEE Bangalore Section" },
    { name: "Kris Gopalakrishnan", college: "Chairman, Axilor Ventures, India" },
    { name: "Kukjin CHUN", college: "Seoul National University, Korea" },
    {
      name: "Lawrence Wong",
      college: "Professor, National University of Singapore",
    },
    { name: "Maniklal Das", college: "Chair, IEEE Gujarat Section" },
    {
      name: "Michael Ong",
      college: "Chair, Conference Committee, IEEE Region 10",
    },
    { name: "Mini Thomas", college: "Director, NIT Trichy, India" },
    { name: "Norliza Mohd Noor", college: "Past Chair, IEEE Malaysia Section" },
    { name: "P.A Manoharan", college: "Chair, IEEE Madras Section" },
  ];
export  const collegeObjects2 = [
    {
      name: "Preeti Bajaj",
      college: "Director, GH Raisoni College of Engineering, India",
    },
    { name: "Prerna Gaur", college: "Chair IEEE Delhi Section" },
    { name: "Puneet K Mishra", college: "Secretary, IEEE India Council." },
    { name: "R.B. Jadeja", college: "Treasurer, IEEE India Council." },
    {
      name: "R.K. Shevgaonkar",
      college: "Vice Chancellor, Bennett University, India",
    },
    { name: "R.V. Raja Kumar", college: "Director, IIT Bhubaneswar, India" },
    {
      name: "Rajnish GUPTA",
      college: "Singapore Institute of Power & Gas, Singapore",
    },
    { name: "Saji Gopinath", college: "CEO, Kerala Startup Mission, India" },
    { name: "Shaikh Fattah", college: "Professor, BUET, Dhaka, Bangladesh" },
    { name: "Sivaji Chakravarti", college: "Director, NIT Calicut, India" },
    { name: "S. K. Varshney", college: "Chair, IEEE Kolkata Section" },
    { name: "S.N. Singh", college: "Chair, IEEE India Council" },
    {
      name: "Sujit K. Biswas",
      college: "Immediate Past Chair, IEEE Kolkata Section",
    },
    { name: "Takako Hashimoto", college: "Secretary, IEEE Region 10" },
    { name: "Thyagarajan K", college: "Professor, IIT Delhi, India" },
    { name: "Tomonori Aoyama", college: "IEEE Chair, IEEE R10 LMAG" },
    { name: "Toshio Fukuda", college: "IEEE President-Elect, Japan" },
    { name: "U.B. Desai", college: "Director, IIT Hyderabad, India" },
    {
      name: "Vincenco Piuri",
      college: "Professor, Universita' degli Studi di Milano, Italy",
    },
    { name: "Y. P. Kosta", college: "Vice Chancellor, Marwadi University" },
    { name: "Zia Ahmed", college: "Vice Chair, IEEE Region 10" },
    {
      name: "Zuhaina Zakaria",
      college: "Professor, Universiti Teknologi Mara, Malaysia",
    },
  ];